  language: python
  python:
    - "3.8"
    - "3.7"
    - "3.6"

  install:
    - pip install -r requirements.txt
    - pip install lazperf

  script:
    - pytest pylas
    - pytest pylastests
    - python -m pytest docs
